# Generated by Django 3.1.2 on 2020-11-25 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201125_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
