# Generated by Django 3.1.2 on 2020-11-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
    ]
