# Generated by Django 3.1.2 on 2020-11-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='abc123', max_length=6),
        ),
    ]
