# Generated by Django 3.1.2 on 2020-11-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_invitation_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyAvailability',
        ),
    ]
