# Generated by Django 3.1.2 on 2020-12-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201203_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('day', models.DateField(default='2010-10-25')),
            ],
        ),
        migrations.RenameModel(
            old_name='WeeklyAvailability',
            new_name='Schedule',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='main.day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='main.day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='main.day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='main.day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='main.day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='main.day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='main.day'),
        ),
        migrations.AlterField(
            model_name='timeframe',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='day_av', to='main.day'),
        ),
        migrations.DeleteModel(
            name='DailyAvailability',
        ),
    ]
