# Generated by Django 3.1.2 on 2020-12-04 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20201203_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekTimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('sunday', 'SUNDAY'), ('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY'), ('saturday', 'SATURDAY')], default=('sunday', 'SUNDAY'), max_length=15)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='team',
            field=models.ManyToManyField(related_name='weekscheduleuser', to='main.Team'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dayscheduleuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekschedule',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekscheduleforteam', to='main.team'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userweekschedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TimeFrame',
        ),
        migrations.AddField(
            model_name='weektimeframe',
            name='weekschedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weektimeframe', to='main.weekschedule'),
        ),
        migrations.AddField(
            model_name='daytimeframe',
            name='dayschedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daytimeframe', to='main.dayschedule'),
        ),
    ]
