# Generated by Django 3.1.2 on 2020-12-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_announcement_daytimeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekschedule',
            name='userTeamValuesDupeCheck',
            field=models.CharField(default='', max_length=100),
        ),
    ]
