# Generated by Django 3.1.2 on 2020-12-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_opusclique_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEvent',
            new_name='SoloEvent',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='not_going',
            new_name='notGoing',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='date_invited',
            new_name='dateInvited',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='invitee_email',
            new_name='inviteeEmail',
        ),
        migrations.AddField(
            model_name='announcement',
            name='clique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clique_announcement', to='main.opusclique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='clique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clique_event', to='main.opusclique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='clique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clique_invitation', to='main.opusclique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cliques',
            field=models.ManyToManyField(related_name='cliques', to='main.Team'),
        ),
    ]
