# Generated by Django 3.1.2 on 2020-12-05 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20201205_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliqueEvent', to='main.opusclique'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(related_name='eventInvited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='notGoing',
            field=models.ManyToManyField(related_name='notGoing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamEvent', to='main.team'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='clique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliqueInvitation', to='main.opusclique'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamInvitation', to='main.team'),
        ),
    ]
