# Generated by Django 3.1.2 on 2020-12-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20201205_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamevent', to='main.opusteam'),
        ),
        migrations.AlterField(
            model_name='event',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamEvent', to='main.opusteam'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamInvitation', to='main.opusteam'),
        ),
        migrations.AlterField(
            model_name='scheduletimeframe',
            name='team',
            field=models.ManyToManyField(related_name='scheduletimeframeteams', to='main.OpusTeam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cliques',
            field=models.ManyToManyField(related_name='opusCliques', to='main.OpusTeam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(related_name='opusTeams', to='main.OpusTeam'),
        ),
    ]
