# Generated by Django 3.1.2 on 2021-01-11 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('793bc623-3cc9-4777-bd74-19bb85265b05'), editable=False, primary_key=True, serialize=False),
        ),
    ]
