# Generated by Django 3.1.2 on 2020-12-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opusclique',
            options={'verbose_name': 'clique', 'verbose_name_plural': 'cliques'},
        ),
        migrations.AlterModelOptions(
            name='opusteam',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
    ]
