# Generated by Django 3.1.2 on 2020-12-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='OpusTeam',
        ),
    ]
