# Generated by Django 3.1.2 on 2020-12-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='main.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.CharField(default='Please join our group.', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.CharField(default='Please let me join our group.', max_length=100),
        ),
    ]
