# Generated by Django 3.1.2 on 2020-12-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201205_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cliques',
            field=models.ManyToManyField(related_name='opusCliques', to='main.OpusClique'),
        ),
    ]
