# Generated by Django 3.1.2 on 2020-12-07 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201206_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(default='thumbs up', max_length=100)),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReactor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='message text', max_length=500)),
                ('sentAt', models.DateTimeField()),
                ('reaction', models.ManyToManyField(related_name='directMessageReaction', to='main.Reaction')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRecipientDM', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSenderDM', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CliqueMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='message text', max_length=500)),
                ('sentAt', models.DateTimeField()),
                ('reaction', models.ManyToManyField(related_name='cliqueMessageReaction', to='main.Reaction')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliqueRecipientCM', to='main.clique')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSenderCM', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
