# Generated by Django 3.1.2 on 2020-12-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201205_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='team',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='team',
        ),
    ]
