# Generated by Django 3.1.2 on 2021-01-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201209_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='clique',
            name='workspace',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
