# Generated by Django 3.1.2 on 2021-01-11 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210111_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliqueEvent', to='main.clique'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, null=True, related_name='eventInvited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='notGoing',
            field=models.ManyToManyField(blank=True, null=True, related_name='notGoing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c3aa45b-5a12-4273-af6c-5eeb7ada7fd1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SoloEvent',
        ),
    ]
