# Generated by Django 3.1.2 on 2020-12-07 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cliquemessage_directmessage_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(default='general', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userToDoList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='laundry', max_length=100)),
                ('due', models.DateTimeField()),
                ('toDoList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toDoToDoList', to='main.todolist')),
            ],
        ),
    ]
