# Generated by Django 3.1.2 on 2021-01-07 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_clique_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creatorAnnouncement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
