# Generated by Django 3.1.2 on 2020-11-14 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201112_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('midnight', models.BooleanField()),
                ('one', models.BooleanField()),
                ('two', models.BooleanField()),
                ('three', models.BooleanField()),
                ('four', models.BooleanField()),
                ('five', models.BooleanField()),
                ('six', models.BooleanField()),
                ('seven', models.BooleanField()),
                ('eight', models.BooleanField()),
                ('nine', models.BooleanField()),
                ('ten', models.BooleanField()),
                ('eleven', models.BooleanField()),
                ('noon', models.BooleanField()),
                ('pone', models.BooleanField()),
                ('ptwo', models.BooleanField()),
                ('pthree', models.BooleanField()),
                ('pfour', models.BooleanField()),
                ('pfive', models.BooleanField()),
                ('psix', models.BooleanField()),
                ('pseven', models.BooleanField()),
                ('peight', models.BooleanField()),
                ('pnine', models.BooleanField()),
                ('pten', models.BooleanField()),
                ('peleven', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='invited',
            field=models.ManyToManyField(related_name='team_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WeekAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('friday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='main.dayavailability')),
                ('monday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='main.dayavailability')),
                ('saturday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='main.dayavailability')),
                ('sunday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='main.dayavailability')),
                ('thursday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='main.dayavailability')),
                ('tuesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='main.dayavailability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_availability', to='main.team')),
                ('wednesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='main.dayavailability')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='event', max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('details', models.CharField(default='This event is blah blah blah..', max_length=100)),
                ('picture', models.CharField(default='pic1', max_length=100)),
                ('invited', models.ManyToManyField(related_name='event_invited', to=settings.AUTH_USER_MODEL)),
                ('not_going', models.ManyToManyField(related_name='not_going', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_event', to='main.team')),
            ],
        ),
    ]
