# Generated by Django 3.1.2 on 2020-12-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201205_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduletimeframe',
            old_name='team',
            new_name='teams',
        ),
    ]
