# Generated by Django 3.1.2 on 2020-12-05 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201205_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ManyToManyField(related_name='teamsSchedule', to='main.OpusTeam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSchedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('sunday', 'SUNDAY'), ('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY'), ('saturday', 'SATURDAY')], default=('sunday', 'SUNDAY'), max_length=15)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('schedules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduleTimeFrame', to='main.schedule')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='clique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliqueAnnouncement', to='main.opusclique'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventAnnouncement', to='main.event'),
        ),
        migrations.DeleteModel(
            name='ScheduleTimeFrame',
        ),
    ]
