# Generated by Django 3.1.2 on 2021-01-18 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210112_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='hi there. please call me Steve.', max_length=160),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43562a28-31db-4fd1-9b03-a1d10a165cae'), editable=False, primary_key=True, serialize=False),
        ),
    ]
