# Generated by Django 3.1.2 on 2020-11-14 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201114_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='invited',
        ),
        migrations.AlterField(
            model_name='team',
            name='announcement',
            field=models.CharField(default='This is a team', max_length=100),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.CharField(default='vansjo01@luther.edu', max_length=100)),
                ('date_invited', models.DateTimeField()),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitation', to='main.team')),
            ],
        ),
    ]
