# Generated by Django 3.1.2 on 2020-12-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201207_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('thumbs up', 'THUMBS UP'), ('dislike', 'DISLIKE')], default=('dislike', 'DISLIKE'), max_length=100),
        ),
    ]
