# Generated by Django 3.1.2 on 2021-01-08 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210107_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventAnnouncement', to='main.event'),
        ),
    ]
