# Generated by Django 3.1.2 on 2020-12-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201205_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeframe',
            old_name='schedules',
            new_name='schedule',
        ),
    ]
