# Generated by Django 3.1.2 on 2021-01-21 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210118_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('56b82ac4-b8f5-4ee7-9139-934fa05dd56a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
