# Generated by Django 3.1.2 on 2021-01-08 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210108_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventAnnouncement', to='main.event'),
        ),
    ]
