# Generated by Django 3.1.2 on 2021-01-08 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210108_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
