# Generated by Django 3.1.2 on 2020-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201114_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayavailability',
            name='eight',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='eleven',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='five',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='four',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='midnight',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='nine',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='noon',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='one',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='peight',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='peleven',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='pfive',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='pfour',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='pnine',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='pone',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='pseven',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='psix',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='pten',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='pthree',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='ptwo',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='seven',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='six',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='three',
        ),
        migrations.RemoveField(
            model_name='dayavailability',
            name='two',
        ),
        migrations.AlterField(
            model_name='dayavailability',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
