# Generated by Django 3.1.2 on 2021-01-21 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210120_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('febdfe64-5c05-4a4a-ac59-25ef6a8681df'), editable=False, primary_key=True, serialize=False),
        ),
    ]
