# Generated by Django 3.1.2 on 2020-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201114_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekavailability',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='weekavailability',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='weekavailability',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='weekavailability',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='weekavailability',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='weekavailability',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='weekavailability',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='weekavailability',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.DeleteModel(
            name='DayAvailability',
        ),
    ]
