# Generated by Django 3.1.2 on 2021-01-21 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210120_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4c328d9-c4ae-42ce-ad5d-0d0e5b537cda'), editable=False, primary_key=True, serialize=False),
        ),
    ]
