# Generated by Django 3.1.2 on 2021-01-09 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210108_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventAnnouncement', to='main.event'),
        ),
    ]
