# Generated by Django 3.1.2 on 2021-01-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210108_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
