# Generated by Django 3.1.2 on 2020-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201125_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='main.Team'),
        ),
    ]
