# Generated by Django 3.1.2 on 2021-01-09 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210108_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='acknowledged',
            field=models.ManyToManyField(related_name='userAnnouncementAcknowledgment', to=settings.AUTH_USER_MODEL),
        ),
    ]
