# Generated by Django 3.1.2 on 2021-01-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_announcement_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='clique',
            name='displayName',
            field=models.CharField(default='group', max_length=30),
        ),
    ]
