# Generated by Django 3.1.2 on 2020-12-02 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201202_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyavailability',
            name='available',
        ),
        migrations.RemoveField(
            model_name='dailyavailability',
            name='availableTimeFrames',
        ),
        migrations.AddField(
            model_name='dailyavailability',
            name='day',
            field=models.DateField(default='2010-10-25'),
        ),
        migrations.AddField(
            model_name='timeframe',
            name='dayAv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='day_av', to='main.dailyavailability'),
        ),
        migrations.AlterField(
            model_name='timeframe',
            name='end',
            field=models.DateTimeField(default='2010-10-25 17:00:00'),
        ),
        migrations.AlterField(
            model_name='timeframe',
            name='start',
            field=models.DateTimeField(default='2010-10-25 09:00:00'),
        ),
    ]
