# Generated by Django 3.1.2 on 2020-12-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201202_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeframe',
            old_name='dayAv',
            new_name='day',
        ),
    ]
