# Generated by Django 3.1.2 on 2020-12-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201203_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='week',
            new_name='weekstart',
        ),
    ]
