# Generated by Django 3.1.2 on 2020-12-03 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201203_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('day', models.DateField(default='2010-10-25')),
            ],
        ),
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='main.dayschedule')),
                ('monday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='main.dayschedule')),
                ('saturday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='main.dayschedule')),
                ('sunday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='main.dayschedule')),
                ('thursday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='main.dayschedule')),
                ('tuesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='main.dayschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule', to=settings.AUTH_USER_MODEL)),
                ('wednesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='main.dayschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='timeframe',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='day_av', to='main.dayschedule'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
