# Generated by Django 3.1.2 on 2020-12-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20201204_0144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayTimeFrame',
        ),
    ]
