# Generated by Django 3.1.2 on 2020-12-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_weekschedule_userteamvaluesdupecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekschedule',
            name='userTeamValuesDupeCheck',
            field=models.CharField(max_length=100),
        ),
    ]
