# Generated by Django 3.1.2 on 2020-12-04 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20201204_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('sunday', 'SUNDAY'), ('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY'), ('saturday', 'SATURDAY')], default=('sunday', 'SUNDAY'), max_length=15)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduletimeframeteam', to='main.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduletimeframeuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='daytimeframe',
            name='dayschedule',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='team',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weektimeframe',
            name='weekschedule',
        ),
        migrations.DeleteModel(
            name='DaySchedule',
        ),
        migrations.DeleteModel(
            name='DayTimeFrame',
        ),
        migrations.DeleteModel(
            name='WeekSchedule',
        ),
        migrations.DeleteModel(
            name='WeekTimeFrame',
        ),
    ]
