# Generated by Django 3.1.2 on 2020-12-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20201204_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletimeframe',
            name='team',
        ),
        migrations.AddField(
            model_name='scheduletimeframe',
            name='team',
            field=models.ManyToManyField(related_name='scheduletimeframeteams', to='main.Team'),
        ),
    ]
