# Generated by Django 3.1.2 on 2020-12-04 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20201204_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitee_email',
            field=models.CharField(default='asdf@example.com', max_length=100),
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Event', max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('details', models.CharField(default='This event is blah blah blah..', max_length=100)),
                ('picture', models.CharField(default='pic1', max_length=100)),
                ('invited', models.ManyToManyField(related_name='userEventInvited', to=settings.AUTH_USER_MODEL)),
                ('not_going', models.ManyToManyField(related_name='usersNotGoing', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEvent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
