# Generated by Django 3.1.2 on 2020-12-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20201204_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='invited',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='not_going',
        ),
    ]
