# Generated by Django 3.1.2 on 2020-12-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_opusteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opusteam',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
