# Generated by Django 3.1.2 on 2020-12-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20201205_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cliques',
            field=models.ManyToManyField(related_name='opusCliques', to='main.Team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(related_name='opusTeams', to='main.Team'),
        ),
    ]
