# Generated by Django 3.1.2 on 2020-12-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20201205_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
